import { ShuttleRoute } from './types';
export type { ShuttleRoute, RouteStatus, RouteStop, RouteAmenities } from './types';

export const MOCK_ROUTES: ShuttleRoute[] = [
  {
    id: 'R-01',
    code: 'R-01',
    name: 'Ruta Norte',
    destination: 'Campus Principal',
    origin: 'Portal Norte',
    status: 'Activo',
    color: '#2563EB', // Blue
    etaMinutes: 4,
    frequencyMinutes: 8,
    capacityPercentage: 58,
    availableSeats: 14,
    totalSeats: 32,
    activeBuses: 4,
    driverName: 'Carlos Mendoza',
    busPlate: 'RG-402',
    amenities: { ac: true, wifi: true, accessible: true },
    stops: [
      { id: 's1', name: 'Portal Norte (Terminal)', estimatedTime: '10:00', isPassed: true },
      { id: 's2', name: 'Estación Biblioteca Central', estimatedTime: '10:08', isCurrent: true },
      { id: 's3', name: 'Complejo Deportivo', estimatedTime: '10:14' },
      { id: 's4', name: 'Campus Principal (Puerta 3)', estimatedTime: '10:20' },
    ],
    scheduleNote: 'Operación continua 06:00 - 21:30',
  },
  {
    id: 'R-02',
    code: 'R-02',
    name: 'Ruta Sur',
    destination: 'Facultad de Medicina',
    origin: 'Estación TransMilenio Sur',
    status: 'Activo',
    color: '#10B981', // Emerald
    etaMinutes: 9,
    frequencyMinutes: 12,
    capacityPercentage: 42,
    availableSeats: 18,
    totalSeats: 30,
    activeBuses: 3,
    driverName: 'Lucía Fernández',
    busPlate: 'RG-118',
    amenities: { ac: true, wifi: false, accessible: true },
    stops: [
      { id: 's5', name: 'Estación Sur', estimatedTime: '09:55', isPassed: true },
      { id: 's6', name: 'Intercambiador Av. Caracas', estimatedTime: '10:05', isCurrent: true },
      { id: 's7', name: 'Hospital San Carlos', estimatedTime: '10:15' },
      { id: 's8', name: 'Facultad de Medicina (Edif. B)', estimatedTime: '10:22' },
    ],
    scheduleNote: 'Operación continua 06:30 - 20:00',
  },
  {
    id: 'R-03',
    code: 'R-03',
    name: 'Ruta Express Central',
    destination: 'Estación Central',
    origin: 'Campus Tecnológico',
    status: 'Demorado',
    statusNote: '+10 min por congestión en Av. El Dorado',
    color: '#F59E0B', // Amber
    etaMinutes: 14,
    frequencyMinutes: 15,
    capacityPercentage: 88,
    availableSeats: 4,
    totalSeats: 34,
    activeBuses: 3,
    driverName: 'Andrés Salamanca',
    busPlate: 'RG-550',
    amenities: { ac: true, wifi: true, accessible: false },
    stops: [
      { id: 's9', name: 'Campus Tecnológico', estimatedTime: '09:50', isPassed: true },
      { id: 's10', name: 'Av. 26 con Cra. 50', estimatedTime: '10:02', isCurrent: true },
      { id: 's11', name: 'Centro de Idiomas', estimatedTime: '10:18' },
      { id: 's12', name: 'Estación Central (Ruta Fácil)', estimatedTime: '10:26' },
    ],
    scheduleNote: 'Servicio semidirecto de alta demanda',
  },
  {
    id: 'R-04',
    code: 'R-04',
    name: 'Ruta Circuito Campus',
    destination: 'Rectoría y Posgrados',
    origin: 'Puerta Principal Av. 30',
    status: 'Activo',
    color: '#8B5CF6', // Purple
    etaMinutes: 2,
    frequencyMinutes: 6,
    capacityPercentage: 35,
    availableSeats: 22,
    totalSeats: 28,
    activeBuses: 2,
    driverName: 'Jorge Ramírez',
    busPlate: 'RG-204',
    amenities: { ac: false, wifi: true, accessible: true },
    stops: [
      { id: 's13', name: 'Puerta 1 (Av. 30)', estimatedTime: '10:00', isPassed: true },
      { id: 's14', name: 'Facultad de Artes y Música', estimatedTime: '10:04', isCurrent: true },
      { id: 's15', name: 'Laboratorios de Ciencias', estimatedTime: '10:09' },
      { id: 's16', name: 'Edificio de Posgrados y Rectoría', estimatedTime: '10:14' },
    ],
    scheduleNote: 'Lanzadera interna gratuita cada 6 minutos',
  },
  {
    id: 'R-05',
    code: 'R-05',
    name: 'Ruta Nocturna Segura',
    destination: 'Zona Residencial Estudiantil',
    origin: 'Plaza de los Estudiantes',
    status: 'Inactivo',
    statusNote: 'Inicia operación a las 18:30 hrs',
    color: '#64748B', // Slate
    etaMinutes: 0,
    frequencyMinutes: 20,
    capacityPercentage: 0,
    availableSeats: 32,
    totalSeats: 32,
    activeBuses: 0,
    driverName: 'Por asignar',
    busPlate: 'RG-310',
    amenities: { ac: true, wifi: true, accessible: true },
    stops: [
      { id: 's17', name: 'Plaza Central', estimatedTime: '18:30' },
      { id: 's18', name: 'Residencias Universitarias Bloque 1', estimatedTime: '18:42' },
      { id: 's19', name: 'Estación de Tren Suburbano', estimatedTime: '18:55' },
    ],
    scheduleNote: 'Servicio de seguridad nocturno 18:30 - 22:30',
  },
];
